const files = [
  "./env.test.js",
  "./idempotency.test.js",
  "./preview-route.test.js",
  "./smoke-imports.test.js",
  "./variants.test.js",
  "./orders-route.test.js",
  "./catalog-route.test.js",
  "./checkout-route.test.js",
  "./order-processing.test.js",
  "./printful-position.test.js",
  "./rate-limiter.test.js",
  "./generation-tracker.test.js",
  "./admin-route.test.js",
  "./watermark.test.js",
  "./session-limiter.test.js",
  "./brand-filter.test.js",
  "./gallery-route.test.js",
  "./referrals.test.js",
  "./generation-queue.test.js",
  "./prompt-cache.test.js",
  "./image-provider.test.js",
  "./service-registry.test.js",
  "./captcha.test.js",
  "./image-moderator.test.js",
  "./dashboard.test.js",
  "./email.test.js",
  "./ab-testing.test.js",
  "./gift-cards.test.js",
  "./auth.test.js",
  "./design-history.test.js",
  "./alerts.test.js",
  "./account-blog.test.js",
];

for (const file of files) {
  await import(file);
}
